### ISSUE TITLE
Is UADetector still updated / maintained ?

### ISSUE THREAD

**Issue by gauthierj** [before/uadetector#107]
Hi, I noticed latest release is from 10/2014 (4 months ago), and that before there was a release every month, so I was wondering if the library is still under development and maintenance. Since things are moving quite fast, especially in mobile world, it is important for a library like that to be updated frequently with new user agents, so I prefer ask the question before starting any development with UADetector.

Thanks, regards,

Gauthier

**Comment by jugglingcats** [comment]
You might want to review the comments on https://github.com/before/uadetector/issues/96.

**Comment by gauthierj** [comment]
Thanks for the info, 

Best regards,

Gauthier
