### ISSUE TITLE
Leak issue

### ISSUE THREAD

**Issue by farchanjo** [before/uadetector#112]
Hi all,
I'm using uadetector to processing my log, but I'm getting a leak on library.

Take a look my implementatation:
```java
@Component
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class UserAgent implements UserAgentStringParser {

    private final UserAgentStringParser parser = UADetectorServiceFactory
            .getCachingAndUpdatingParser();
    private final Cache<String, ReadableUserAgent> cache = CacheBuilder.newBuilder()
            .maximumSize(100)
            .expireAfterWrite(30, TimeUnit.SECONDS)
            .build();

    @Override
    public String getDataVersion() {
        return parser.getDataVersion();
    }

    @SuppressWarnings("NullableProblems")
    @Override
    public ReadableUserAgent parse(final String userAgentString) {
        ReadableUserAgent result = cache.getIfPresent(userAgentString);
        if (result == null) {
            result = parser.parse(userAgentString);
            cache.put(userAgentString, result);
        }
        return result;
    }

    @Override
    public void shutdown() {
        parser.shutdown();
    }
}
```

Afterall, I call this component on processor,

```java
 String ua = webLog.feed(nginxParser.clean(line)).getUa();
        ReadableUserAgent a = userAgent.parse(ua);
        a.toString();
        userAgent.shutdown();
```

Even thought there a lot of regex instances.

![screenshot 2015-04-16 21 12 28](https://cloud.githubusercontent.com/assets/4031556/7193915/51c5bf72-e47d-11e4-8d22-21e3755cc8e7.png)

am I doing something wrong?

Thanks all

**Comment by before** [comment]
@farchanjo hard to tell without any glue about your logs. But I would increase the maximum size of the cache. 100 entries seems too limited for my taste. I would go with something around 10.000 and 100.000. User agent strings can vary subtle, especially if it comes to browsers.

**Comment by farchanjo** [comment]
I have live parsing from my apaching log. It's about 100 lines per seconds, but ok.

Thanks u so much.

**Comment by before** [comment]
I would count the distinct entries over a bigger interval. Maybe start with 30 minutes to get an overview how often you would parse the same strings again. Tweaking the cache to save CPU cycles is a tough thing.
